#!/bin/bash
# Script para configurar correctamente Vercel

echo "=== Configuración de Vercel ==="
echo ""
echo "Para que tu frontend se despliegue correctamente en Vercel, sigue estos pasos:"
echo ""
echo "1. Ve a https://vercel.com/dashboard"
echo "2. Abre tu proyecto 'whatsapp' (o similar)"
echo "3. Ve a Settings > Environment Variables"
echo "4. Añade estas variables:"
echo ""
echo "   Variable: VITE_API_URL"
echo "   Value: https://TU-BACKEND-URL/api/trpc"
echo ""
echo "5. En la configuración del proyecto, asegúrate que el Output Directory sea: dist/public"
echo "   y que no haya propiedades inválidas en vercel.json (por ejemplo: public, env, envFile)"
echo ""
echo "6. Redeploy el proyecto"
echo ""
echo "=== Siguientes pasos ==="
echo ""
echo "Tu frontend se verá en: https://rubwp.vercel.app"
echo "Tu backend debe estar en: https://TU-BACKEND-URL"
echo ""
echo "Opciones para backend:"
echo "  - Render.com (recomendado)"
echo "  - Railway.app"
echo "  - Fly.io"
echo ""
echo "Ver: DEPLOYMENT_VERCEL.md para instrucciones detalladas"
